import store from "@/store/store";
import "@/styles/globals.css";
import Head from "next/head";
import { useRouter } from "next/router";
import { Provider } from "react-redux";
import Navbar from "./Components/Navbar";

export default function App({ Component, pageProps }) {
  const router = useRouter();
  if (router.pathname !== "/_error") {
    return (
      <Provider store={store}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <Component {...pageProps} />
      </Provider>
    );
  }

  return (
    <Provider store={store}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />;
    </Provider>
  );
}
